In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import joblib

In [ ]:
file_add = "/content/drive/MyDrive/apadamitra_cyclone_dataset.csv"
df = pd.read_csv(file_add)
df.head()

   Sea_Surface_Temperature  ...  Cyclone
0                27.498160  ...        1
1                28.404460  ...        1
2                27.216969  ...        1
3                27.824280  ...        1
4                26.260206  ...        1

[5 rows x 7 columns]

In [ ]:
df.shape

(2000, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Sea_Surface_Temperature  2000 non-null   float64
 1   Atmospheric_Pressure     2000 non-null   float64
 2   Humidity                 2000 non-null   float64
 3   Wind_Shear               2000 non-null   float64
 4   Latitude                 2000 non-null   float64
 5   Proximity_to_Coastline   2000 non-null   float64
 6   Cyclone                  2000 non-null   int64
dtypes: float64(6), int64(1)
memory usage: 109.5 KB

In [ ]:
df['Cyclone'].value_counts()

Cyclone
1    1000
0    1000
Name: count, dtype: int64

In [ ]:
X = df.drop('Cyclone', axis=1)
y = df['Cyclone']

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Sea_Surface_Temperature  2000 non-null   float64
 1   Atmospheric_Pressure     2000 non-null   float64
 2   Humidity                 2000 non-null   float64
 3   Wind_Shear               2000 non-null   float64
 4   Latitude                 2000 non-null   float64
 5   Proximity_to_Coastline   2000 non-null   float64
dtypes: float64(6)
memory usage: 93.9 KB

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
model = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    random_state=42
)

In [ ]:
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=12, n_estimators=300, random_state=42)

In [ ]:
pred = model.predict(X_test)

In [ ]:
print("Accuracy:",accuracy_score(y_test,pred))

Accuracy: 0.995

In [ ]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       200
           1       0.99      1.00      1.00       200

    accuracy                           0.99       400
   macro avg       1.00      0.99      0.99       400
weighted avg       1.00      0.99      0.99       400

In [ ]:
joblib.dump(
    model,
    "apadamitra_cyclone_model.pkl"
)
joblib.dump(
    scaler,
    "apadamitra_cyclone_scaler.pkl"
)

['apadamitra_cyclone_scaler.pkl']